version: "3.8"
services:
  app: 
    build: .
    restart: 'always'
    depends_on:
      - postgres-db
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app/
      - /app/node_modules

  postgres-db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=community_db
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data: {}